version: "2"
services:
  web:
    image: node
    command: npm start --prefix /usr/app
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql
    volumes:
        - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: art_meets_emoji
        MYSQL_USER: user
        MYSQL_PASSWORD: password
